# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-19 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aptechtutor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='hide',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='hide',
            field=models.BooleanField(default=False),
        ),
    ]
