# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-19 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aptechtutor', '0002_auto_20160919_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='hide',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='hide',
            field=models.CharField(max_length=5),
        ),
    ]
